spring.application.name=accounting-app
app.datasource.writer.url=jdbc:h2:mem:accountingdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
app.datasource.writer.driver-class-name=org.h2.Driver
app.datasource.writer.username=sa
app.datasource.writer.password=
app.datasource.reader.url=jdbc:h2:mem:accountingdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
app.datasource.reader.driver-class-name=org.h2.Driver
app.datasource.reader.username=sa
app.datasource.reader.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
